services:
  karavan:
    image: ghcr.io/apache/camel-karavan:4.5.0
    ports:
      - "8080:8080"
    environment:
      KARAVAN_GIT_REPOSITORY: https://github.com/VARA-2213/karavan-projects.git
      KARAVAN_GIT_USER: Karavan


      KARAVAN_GIT_PASSWORD: your-password-or-token
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest

      RABBITMQ_DEFAULT_PASS: guest

