services:
  rabbit-mq-test:
    image: rabbit-mq-test
    restart: always
    ports:
      - "8083:8080"
    networks:
      - karavan
    environment:
      - MQ_USER=guest
      - MQ_PASSWORD=guest